resolver: nightly-2020-06-25

packages:
  - .
  - ../chart-svg
  - ../numhask
  - ../numhask-space
  - ../numhask-array
  - ../mealy
  - ../box

extra-deps:
  - backprop-0.2.6.4
  #- box-0.6.0
  - box-csv-0.0.2
  #- box-socket-0.0.2
  # - chart-svg-0.2.0
  #- git: https://github.com/tonyday567/chart-svg
  #  commit: e880d0c42501e500eccea87a0aba33b8f25dd54e
  #- numhask-0.6.0.2
  #- numhask-array-0.7.0
  #- numhask-space-0.6.0
  #- mealy-0.0.1
  - vinyl-0.13.0
  #- web-rep-0.7.0
  - reanimate-1.1.1.0
  - reanimate-svg-0.13.0.0
  - hgeometry-0.11.0.0
  - hgeometry-combinatorial-0.11.0.0

